//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.SANPHAMYEUTHICHes = new HashSet<SANPHAMYEUTHICH>();
        }
    
        public string MA { get; set; }
        public string TEN { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> LOAISANPHAM { get; set; }
        public Nullable<int> NHASANXUAT { get; set; }
        public Nullable<bool> DAXOA { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM1 { get; set; }
        public virtual NHASANXUAT NHASANXUAT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAMYEUTHICH> SANPHAMYEUTHICHes { get; set; }
    }
}
