//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNGDUNG
    {
        public int MA { get; set; }
        public string TENDANGNHAP { get; set; }
        public string MATKHAU { get; set; }
        public string TEN { get; set; }
        public string DOMAINURL { get; set; }
        public string MAKICHHOAT { get; set; }
        public Nullable<bool> DAXOA { get; set; }
    }
}
